plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.1'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com'
version = '0.0.1-SNAPSHOT'
description = 'public-boot'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

ext {
    springAiVersion = '2.0.1'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.ai:spring-ai-bom:${springAiVersion}"
    }
}

dependencies {
    // Boot
    implementation 'org.springframework.boot:spring-boot-starter-cache'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'

    // DB
    runtimeOnly 'org.postgresql:postgresql:42.7.13'
    runtimeOnly 'org.xerial:sqlite-jdbc:3.53.2.1'

    // Mybatis
    // implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:4.1.0'

    // Caffeine
    implementation 'com.github.ben-manes.caffeine:caffeine:3.2.4'

    // ModelMapper
    implementation 'org.modelmapper:modelmapper:3.2.4'

    // Poi
    implementation 'org.apache.poi:poi-ooxml:5.5.1'

    // Spring AI - Google Gemini
    implementation 'org.springframework.ai:spring-ai-starter-model-google-genai'

    // Google
    implementation 'com.google.api-client:google-api-client:2.9.0'

    // Jasypt
    implementation 'com.github.ulisesbocchio:jasypt-spring-boot-starter:4.0.4'

    // AWS
    implementation 'software.amazon.awssdk:s3:2.52.0'
    implementation 'software.amazon.jdbc:aws-advanced-jdbc-wrapper:4.3.0'

    // JJWT
    implementation 'io.jsonwebtoken:jjwt-api:0.13.0'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.13.0'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.13.0'

    // Test
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}
